### ISSUE TITLE
Question: How to implement Global Exception Handler?

### ISSUE THREAD

**Issue by dilaragorum** [slack-samples/bolt-java-starter-template#199]
Hello, thank you for this great boilerplate. I enjoyed to do development on it. ❤️  I want to ask a question.

How can I define [global exception handler](https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice) one place in order to handle all IOException, SlackAPIException, could you please me right direction?

In the boilerplate, all of codes has try and catch statement, is this only way to handle exceptions? 

Also, using executor service is really necessary? Do I have to use it?

Thanks 🙏

**Comment by seratch** [comment]
Hi @dilaragorum, thanks for asking the question!

>How can I define [global exception handler](https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice) one place in order to handle all IOException, SlackAPIException, could you please me right direction?

Currently, Bolt framework does not have such mechanism. That being said, the default error handlers in the adapter modules could be to simple and there is no way to customize it without forking the code (example: https://github.com/slackapi/java-slack-sdk/blob/v1.35.0/bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java#L67-L69). This can be improved, so we will add an option to pass a function to override it in future versions.

>In the boilerplate, all of codes has try and catch statement, is this only way to handle exceptions?

Yes, this is the approach we recommend for error patterns. The reason is that only listeners can return a meaningful response to Slack for suitable user experience. For instance, if your app code unexpectedly gets an error while handling slash commands / modal data submission, your app needs to tell what happened to the end-user. To do this, your app needs to return a response with text in a proper way (e.g., in catch clause, returning text to a slash command request, updating the existing modal to display an error using views.update API method).

>Also, using executor service is really necessary? Do I have to use it?

Not always but it should be useful in many cases. Your app must respond within 3 seconds for interactivity patterns (e.g., slash commands, button clicks, etc.) and Events API handling. This can be a tough requirement when you need to wait for other backend service responses. Otherwise, when you're confident that your app does not take any longer than 3 seconds for sure, you don't need to use executor service or similar to do something async.

**Comment by seratch** [comment]
This issue has been inactive for a while, so let me close it now. Thank you for posting the question!
